apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsevice-challenge-1
  labels:
    app: microsevice-challenge-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microsevice-challenge-1
  template:
    metadata:
      labels:
        app: microsevice-challenge-1
    spec:
      containers:
        - name: microsevice-challenge-1
          image: jdiegobonp/microsevice-challenge-1:latest
          ports:
            - containerPort: 5000